---
- name: Check for uninstall signal
  command: /bin/true
  notify: Uninstall systemd units
  when: perform_uninstall

- name: End play following uninstallation
  meta: end_play
  when: perform_uninstall

- name: Include common config tasks
  include_tasks: "common/config.yml"
  tags:
    - config
