---
- name: Include common preflight tasks
  include_tasks: "common/preflight.yml"
  tags:
    - config

- name: Include common config tasks
  include_tasks: "common/config.yml"
  tags:
    - config

- name: Include common launch tasks
  include_tasks: "common/launch.yml"
  tags:
    - launch
