---
- name: Reload systemd units
  become: true
  systemd:
    name: "{{ restart_item.dest | basename }}"
    state: "{{ 'restarted' if unit_requested_state == 'started' else unit_requested_state }}"
    daemon_reload: true
  vars:
    unit_requested_state: "{{ restart_item.unit_item.state | default(_default_unit_state) }}"
  when: restart_item.changed
  with_items: "{{ restart_units.results }}"
  loop_control:
    loop_var: restart_item
  listen: "Reload systemd units"
  ignore_errors: true

- name: Uninstall systemd units
  become: true
  systemd:
    name: "{{ unit_item.name }}.{{ unit_item.type | default(_default_unit_type) }}"
    state: "stopped"
    enabled: "no"
  with_items: "{{ unit_config }}"
  loop_control:
    loop_var: unit_item
  listen: Uninstall units
  ignore_errors: true

- name: Remove managed systemd unit files
  become: true
  file:
    path: "{{ unit_item.path | default(_default_unit_path) }}/{{ unit_item.name }}.{{ unit_item.type | default(_default_unit_type) }}"
    state: absent
  listen: Uninstall units
  with_items: "{{ unit_config }}"
  loop_control:
    loop_var: unit_item
