---
- name: Reload systemd units
  become: true
  systemd:
    name: "{{ item.dest | basename }}"
    daemon_reload: true
  with_items: "{{ restart_units.results }}"
  listen: "Reload systemd units"

- name: Remove managed systemd unit files
  become: true
  file:
    path: "{{ item.path | default(_default_unit_path) }}/{{ item.name }}.{{ item.type | default(_default_unit_type) }}"
    state: absent
  listen: Uninstall config
  with_items: "{{ unit_config }}"
