---
- name: Define unit({{ unit.name }}) path and type attributes
  set_fact:
    unit_path: "{{ unit.path|default(_default_unit_path) }}"
    unit_type: "{{ unit.type|default(_default_unit_type) }}"
  tags:
    - preflight
    - config

- name: Render unit({{ unit.name }}) configuration
  template:
    src: "systemd.unit.j2"
    dest: "{{ unit_path }}/{{ unit.name }}.{{ unit_type }}"
    owner: "root"
    group: "root"
    mode: 0644
    backup: true
  vars:
    config: "{{ unit }}"
  tags:
    - config
