---
- name: Check for uninstall signal
  when: perform_uninstall
  block:
    - name: Broadcast uninstall signal
      command: /bin/true
      notify:
        - Uninstall config
  rescue:
    - name: Ensure flush of handlers
      meta: flush_handlers
  tags:
    - preflight
